CREATE TABLE UserFile (
    sha1 VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    dir VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    upload_at DATETIME NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
